[package]
name = "vocaloid"
version = "0.1.1"
edition = "2021"
description = "Real-time voice synthesis interface for rasberrypi OSAI Vocaloid systems."
license = "MIT"
readme = "README.md"
keywords = ["OSAI","tool","vocaloid"]
repository = "https://github.com/amyoshi-hub/Vocaloid-AI/tree/main/Vocaloid"


[dependencies]
fileio_handle = "0.1.0"
hound = "3.5.1"
local-ip-address = "0.6.5"
